# Generated by Django 5.1 on 2024-08-30 23:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unlikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_unlike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_who_unliked', to='network.post')),
                ('user_unlike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_who_unliked', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
