# Generated by Django 5.1 on 2024-08-30 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_unlikes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Unlikes',
        ),
    ]
